/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "asd.check" instead.
 */

#include <check.h>
#include <stdio.h>

#include "../model_operations.h"
#include "../parser.h"

START_TEST(parser) {
  Vertex v;
  Surface s;
  int err = Parse("model/tests/test.obj", &v, &s);
  ck_assert_int_eq(ALL_GOOD, err);
  FreeSurface(&s);
  FreeVertex(&v);
  err = Parse("model/tests/111.obj", &v, &s);
  ck_assert_int_eq(ERROR_OPENING_FILE, err);
  err = Parse("model/tests/lamp.obj", &v, &s);
  ck_assert_int_eq(ALL_GOOD, err);
  FreeSurface(&s);
  FreeVertex(&v);
}
END_TEST

START_TEST(free_test) {
  Vertex v;
  Surface s;
  int err = 0;
  Parse("model/tests/test.obj", &v, &s);
  FreeVertex(&v);
  if (v.data != NULL) err = 1;
  ck_assert_int_eq(0, err);

  FreeSurface(&s);
  if (s.polygons != NULL) err = 1;
  ck_assert_int_eq(0, err);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, parser);
  tcase_add_test(tc1_1, free_test);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
